//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleTable.List
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;
    using CommonLibrary.Base.Database;
    
    /// <summary>
    /// Class to service as a list of DTO objects and also fills the DTO objects using the SqlDataReader when passed in
    /// To the relevant constructor.  Attributed to indicate the Table in the database that this would be in relation to
    /// </summary>
    [CommonLibrary.CustomAttributes.TableNameAttribute("Folks")]
    public class Folks : List<Data.SingleTable.Dto.Folks>
    {        
        private CommonLibrary.Base.Database.BaseDatabase _baseDatabase = new CommonLibrary.Base.Database.BaseDatabase();
        
        public Folks(System.Data.SqlClient.SqlDataReader reader)
        {
            this.AddItemsToListBySqlDataReader(reader);
        }
        
        public Folks()
        {
        }
        
        public virtual void AddItemsToListBySqlDataReader(System.Data.SqlClient.SqlDataReader reader)
        {
        
            Data.SingleTable.Dto.Folks dto;
                using(reader)
                {

                while(reader.Read())
                {
            dto = new Data.SingleTable.Dto.Folks();
                    dto.FirstName = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("FirstName"), reader);
                    dto.LastName = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("LastName"), reader);
                    dto.BirthLocation = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("BirthLocation"), reader);
                    dto.Bio = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("Bio"), reader);
                    dto.ID = 
                    _baseDatabase.resolveNullInt32(reader.GetOrdinal("ID"), reader);
                    this.Add(dto);
                }

                }

        }
    }
}
