//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.SingleTable.Dto
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using CommonLibrary;
    
    /// <summary>
    /// Class that is basically a pure DTO, it is mean to transfer data and maps directly to a database table,
    /// it is attributed to indicate the table from which it is meant to model
    /// </summary>
    [CommonLibrary.CustomAttributes.TableNameAttribute("Folks")]
    public class Folks
    {
        
        private string _firstName;
        
        private string _lastName;
        
        private string _birthLocation;
        
        private string _bio;
        
        private int _iD;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public Folks()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("FirstName")]
        public virtual string FirstName
        {
            get
            {
                return this._firstName;
            }
            set
            {
                this._firstName = value;
                this.SetIsModified("FirstName");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("LastName")]
        public virtual string LastName
        {
            get
            {
                return this._lastName;
            }
            set
            {
                this._lastName = value;
                this.SetIsModified("LastName");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("BirthLocation")]
        public virtual string BirthLocation
        {
            get
            {
                return this._birthLocation;
            }
            set
            {
                this._birthLocation = value;
                this.SetIsModified("BirthLocation");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("Bio")]
        public virtual string Bio
        {
            get
            {
                return this._bio;
            }
            set
            {
                this._bio = value;
                this.SetIsModified("Bio");
            }
        }
        
        [CommonLibrary.CustomAttributes.DatabaseColumnAttribute("ID")]
        [CommonLibrary.CustomAttributes.PrimaryKey()]
        public virtual int ID
        {
            get
            {
                return this._iD;
            }
            set
            {
                this._iD = value;
                this.SetIsModified("ID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("FirstName", false);
            this.IsModifiedDictionary.Add("LastName", false);
            this.IsModifiedDictionary.Add("BirthLocation", false);
            this.IsModifiedDictionary.Add("Bio", false);
            this.IsModifiedDictionary.Add("ID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
